# Generated by Django 4.2 on 2025-05-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patient_blood_group_patient_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='additional_image1',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_additional/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='additional_image2',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_additional/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_certificates/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_clinics/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='additional_image',
            field=models.ImageField(blank=True, null=True, upload_to='patient_additional/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='patient_insurance/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_record_image',
            field=models.ImageField(blank=True, null=True, upload_to='patient_medical_records/'),
        ),
    ]
