# Generated by Django 4.2 on 2025-05-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_doctor_additional_image1_doctor_additional_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='additional_image1',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='additional_image2',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='certificate_image',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='clinic_image',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='additional_image',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_card_image',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medical_record_image',
        ),
    ]
