# Generated by Django 5.0.1 on 2025-05-30 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_doctor_additional_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='total_reviews',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
